---
- name: this playbokk copy the file from server to nodes
  hosts: web
  become: true
  tasks:
  - name: copy file from server to nodes "index.html"
    copy: 
     src: /home/ansadmin/index.ht
     dest: /home/ansadm
     mode: 700
     owner: raju
     group: rohit
